[package]
name = "application-database"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
application-kernel = { path = "../application-kernel" }

chrono = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

ulid = { workspace = true }

sqlx = { version = "0.8.0", features = [ "runtime-tokio", "tls-rustls", "mysql", "chrono" ] }

totp-rs = { version = "5.7.0", features = ["otpauth"] }
