name: Coding Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-backend:
    name: "Backend: Check"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application-rs
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cache crates
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Run cargo check
        run: |
          cargo check --all-features

  lint-backend:
    name: "Backend: Lint"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application-rs
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Cache crates
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Run cargo fmt
        run: |
          cargo fmt --all -- --check
      - name: Run cargo clippy
        run: |
          cargo clippy -- -D warnings

  test-backend:
    name: "Backend: Test"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application-rs
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cache crates
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Run cargo test
        run: |
          cargo test --all-features

  lint-frontend-yansongda:
    name: "Frontend: Lint (Yansongda)"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wechat/miniprogram/yansongda
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Setup Deno
        uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: |
          deno install
      - name: Run biome check
        run: |
          deno task biome:check
      - name: Run type check
        run: |
          deno task typecheck

  lint-frontend-totp:
    name: "Frontend: Lint (TOTP)"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wechat/miniprogram/totp
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Setup Deno
        uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: |
          deno install
      - name: Run biome check
        run: |
          deno task biome:check
      - name: Run type check
        run: |
          deno task typecheck
